// SPDX-License-Identifier: MIT
// Deterministic, dependency-free asset generator. Run from any directory.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { faces, rasterFace } from './designs.js';
const sourceDirectory = path.dirname(fileURLToPath(import.meta.url));

function packPixels(pixels) {
  if (pixels.length !== 128 * 32) throw new RangeError('Expected 4096 pixels');
  const bytes = Buffer.alloc(512);
  pixels.forEach((pixel, i) => {
    if (pixel !== 0 && pixel !== 1) throw new RangeError('Expected binary pixels');
    bytes[i >> 3] |= pixel << (7 - (i & 7));
  });
  return bytes;
}

function encodeRle(bytes) {
  const result = [];
  for (let i = 0; i < bytes.length;) {
    const value = bytes[i];
    let count = 1;
    while (count < 255 && i + count < bytes.length && bytes[i + count] === value) count++;
    result.push(count, value);
    i += count;
  }
  return Buffer.from(result);
}

function buildAssets() {
  const unique = [], indices = [], animations = [], seen = new Map();
  for (const face of faces) {
    const frames = [], sequence = [];
    for (let i = 0; i < 30; i++) {
      // 2.6 seconds of motion, then four frames of the resting pose.
      const frame = packPixels(rasterFace(face.id, i < 26 ? i / 10 : 0));
      const key = frame.toString('hex');
      if (!seen.has(key)) {
        seen.set(key, unique.length);
        unique.push(frame);
      }
      frames.push(frame);
      sequence.push(seen.get(key));
    }
    animations.push(frames);
    indices.push(sequence);
  }
  const offsets = [0], chunks = [];
  for (const frame of unique) {
    const encoded = encodeRle(frame);
    chunks.push(encoded);
    offsets.push(offsets[offsets.length - 1] + encoded.length);
  }
  const data = Buffer.concat(chunks);
  if (faces.length !== 16 || unique.length > 256 || data.length > 65535) {
    throw new RangeError('Asset count exceeds the C++ table format');
  }
  return { animations, unique, indices, offsets, data };
}

function outputs(assets) {
  const lines = [
    '// SPDX-License-Identifier: MIT',
    '// Generated by scripts/expressions/generate.js. Do not edit by hand.',
    '#pragma once',
    '#include "TinyEngineerExpressions.h"',
    'namespace tiny_engineer { namespace expressions { namespace detail {',
    `constexpr std::size_t kUniqueFrameCount = ${assets.unique.length};`,
    `constexpr std::size_t kRleDataSize = ${assets.data.length};`,
    'const uint8_t kRleData[kRleDataSize] TE_EXPR_PROGMEM = {'
  ];
  for (let i = 0; i < assets.data.length; i += 24) {
    lines.push('  ' + [...assets.data.subarray(i, i + 24)].map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',');
  }
  lines.push('};', 'const uint16_t kFrameOffsets[kUniqueFrameCount + 1] TE_EXPR_PROGMEM = {');
  for (let i = 0; i < assets.offsets.length; i += 12) lines.push('  ' + assets.offsets.slice(i, i + 12).join(', ') + ',');
  lines.push('};', 'const uint8_t kFrameIndices[kExpressionCount][kFramesPerExpression] TE_EXPR_PROGMEM = {');
  assets.indices.forEach((sequence, i) => lines.push('  {' + sequence.join(', ') + '}, // ' + faces[i].id));
  lines.push('};', '}}} // namespace tiny_engineer::expressions::detail', '');
  const manifest = {
    width: 128, height: 32, format: 'row-major-msb-first', frameMs: 100, loopMs: 3000,
    expressions: faces.map((face, i) => ({
      id: face.id, frames: 30,
      sha256: crypto.createHash('sha256').update(Buffer.concat(assets.animations[i])).digest('hex')
    })),
    totalFrames: 480, uniqueFrames: assets.unique.length, rleBytes: assets.data.length,
    indexBytes: 480, offsetBytes: assets.offsets.length * 2,
    assetBytes: assets.data.length + 480 + assets.offsets.length * 2
  };
  const root = path.resolve(sourceDirectory, '../..');
  return new Map([
    [path.join(root, 'lib/TinyEngineerExpressions/src/expression_assets.h'), lines.join('\n')],
    [path.join(sourceDirectory, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n']
  ]);
}

function generate(check = false) {
  const assets = buildAssets();
  for (const [filename, content] of outputs(assets)) {
    if (check) {
      if (!fs.existsSync(filename) || fs.readFileSync(filename, 'utf8') !== content) {
        throw new Error('Generated assets are stale: ' + path.basename(filename));
      }
    } else {
      fs.mkdirSync(path.dirname(filename), { recursive: true });
      fs.writeFileSync(filename, content);
    }
  }
  console.log(`${check ? 'Verified' : 'Generated'} 16 expressions, 480 frames, ${assets.unique.length} unique frames; ${assets.data.length + 480 + assets.offsets.length * 2} asset bytes.`);
}

export { packPixels, encodeRle, buildAssets, generate };
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('Usage: node generate.js [--check]');
  generate(process.argv.includes('--check'));
}
