Import("env")

import gzip
import shutil
import subprocess
from pathlib import Path

project_dir = Path(env.subst("$PROJECT_DIR"))
ui_dir = project_dir / "ui"
generated_dir = Path(env.subst("$BUILD_DIR")) / "generated"
header = generated_dir / "web_ui.h"


def npm(*args):
    executable = shutil.which("npm")
    if executable is None:
        raise RuntimeError("npm not found; building the web UI needs Node 20.19+ on 20.x, or 22.12+")
    subprocess.run([executable, *args], cwd=ui_dir, check=True)


def newest_source_mtime():
    sources = [ui_dir / "index.html", ui_dir / "vite.config.js", ui_dir / "package-lock.json"]
    sources += [path for path in (ui_dir / "src").rglob("*") if path.is_file()]
    return max(path.stat().st_mtime for path in sources)


env.Append(CPPPATH=[str(generated_dir)])

# pio runs pre-scripts for every target (uploadfs, otafs, ...), so skip Node when ui/ is unchanged.
if header.is_file() and header.stat().st_mtime >= newest_source_mtime():
    Return()

# npm writes this marker on install; an older one means the lockfile changed since.
installed = ui_dir / "node_modules" / ".package-lock.json"
if not installed.is_file() or installed.stat().st_mtime < (ui_dir / "package-lock.json").stat().st_mtime:
    npm("ci")
npm("run", "build")

page = (ui_dir / "dist" / "index.html").read_bytes()
# mtime=0 keeps the bytes identical for identical sources, so an unchanged UI does not rebuild index_page.cpp.
packed = gzip.compress(page, compresslevel=9, mtime=0)
rows = ",\n".join(
    "  " + ", ".join(f"0x{byte:02x}" for byte in packed[offset:offset + 16])
    for offset in range(0, len(packed), 16)
)
source = (
    "// Generated by scripts/embed_ui.py from ui/. Do not edit.\n"
    "#pragma once\n\n"
    "#include <Arduino.h>\n\n"
    f"const uint8_t kWebUiGzip[] PROGMEM = {{\n{rows}\n}};\n"
)

generated_dir.mkdir(parents=True, exist_ok=True)
if header.is_file() and header.read_text() == source:
    header.touch()
else:
    header.write_text(source)
print(f"Embedded web UI: {len(page)} -> {len(packed)} bytes gzipped")
